services:
  redis:
    container_name: redis
    image: redis:7.2
    networks:
      - main
    volumes:
      - redis_data:/data

  

volumes:
  redis_data:

networks:print("hello")
  main:
    driver: bridge
